lua/noice/view/virtualtext.lua
this fixes interrupted highlighting when virtualtext is displayed inside the `cursorline`
=> fix: set hl_mode combine for virtualtext

lua/noice/view/nui.lua
\#117 Added the smart_move function that avoids overlap. But it introduced some bugs with cmdline view set to `cmdline`. To avoid overlap with `mini` or other views, the cmdline itself would move to odd locations. This fixes that issue.
=> fix(smart_move): Dont move `cmdline` view

lua/telescope/_extensions/noice.lua
Use `Config.options.commands.history` instead of `Config.options.history`
Its a new regression that caused errors when using `Noice telescope`
=> fix(telescope): Correct index for finder

lua/noice/commands.lua, lua/noice/lsp/message.lua, lua/noice/lsp/progress.lua, lua/noice/message/filter.lua, lua/noice/message/init.lua, lua/noice/message/manager.lua, lua/noice/message/router.lua, lua/noice/source/notify.lua, lua/noice/text/format/init.lua, lua/noice/ui/msg.lua, lua/noice/util/hacks.lua, lua/noice/view/backend/mini.lua, lua/noice/view/backend/notify.lua, lua/noice/view/backend/notify_send.lua, lua/noice/view/init.lua, lua/noice/view/nui.lua
Message state is currently managed Neovim `msg_clear` events, which lead to all sorts of problems, since Noice is more than just Neovim messages.
The new implementation no longer uses `msg_clear` events.
Incoming messages are now routed directly to the correct views. Views manage message state:
- notify/mini: clear messages once the message has been dispatched into the view
- nui views: clear messages on close of the view
=> feat: manage message state without msg_clear

lua/noice/util/hacks.lua
Currently, the popupmenu position of `cmp` is not aligned with input of smart-cmdline, because of its offset. Adjust the screen cursor position with offset should fix it. I try to access the offset directly by `Cmdline.last().offset`, but I'm not sure it's the right way.
**Before**
**After**
=> fix: cmp popupmenu position

lua/noice/config/init.lua
Show proper prompt for the expression register. Press `<c-r>=` in insert mode to see how it looks like.
=> feat(config): add calculator to cmdline formats

lua/noice/message/init.lua
Before this change, adding `<esc>` to `lsp.documentation.close.keys` would result in the window being closed immediately after getting focus.
=> Allow mapping `<esc>`

README.md, lua/noice/config/init.lua, lua/noice/ui/cmdline.lua
Hey @folke there was a new commit on nightly https://github.com/neovim/neovim/commit/a92b38934a2d00c13ee4d1969d994da15e0857ab with a shorthand syntax `:=` for `:lua` cmdline. This feature is to match the pattern and format with the lua icon.
My autoformatter added the whitespace, let me know if you want me to remove it. 
> The `:= {expr}` syntax can be used to evaluate a lua expression, as
a shorter form of `:lua ={expr}`. `:=` and `:[range]=` without argument
are unchanged. However `:=#` and similar variants using |ex-flags|
are no longer supported.
=> feat(cmdline): Add format for := lua expr

lua/noice/health.lua
health api was changed in [#22927](https://github.com/neovim/neovim/pull/22927)
```help
- *health#report_error* *vim.health.report_error()*	Use |vim.health.error()| instead.
- *health#report_info* *vim.health.report_info()*	Use |vim.health.info()| instead.
- *health#report_ok* *vim.health.report_ok()*		Use |vim.health.ok()| instead.
- *health#report_start* *vim.health.report_start()*	Use |vim.health.start()| instead.
- *health#report_warn* *vim.health.report_warn()*	Use |vim.health.warn()| instead.
```
=> chore: update healthcheck

lua/noice/lsp/signature.lua
I noticed the same issue as described in https://github.com/folke/noice.nvim/issues/162 come up for me while using `nimlsp`. 
This adds checks for the existence of  `sig.parameters` before trying to index it.
=> safer lsp signature parameters

lua/noice/text/markdown.lua, tests/text/markdown_spec.lua
Adds a few missing html entities.
Aligns with https://github.com/neovim/neovim/blob/26cc946226d96bf6b474d850b961e1060346c96f/runtime/lua/vim/lsp/util.lua#L1382
Fixes #447
=> fix(html): add additional html entities

lua/noice/lsp/signature.lua
In some circumstances, the arguments of autocommand callback hold a `nil` in `data` field.
It's better to skip it.
=> fix(lsp): add non-nil guard to setup function

lua/telescope/_extensions/noice.lua
A [Telescope](https://github.com/nvim-telescope/telescope.nvim) picker is a great way for previewing diagnostics, but is problematic when previewing long diagnostic strings, as it only allows vertical scrolling.
Setting the _'wrap'_ option in the previewer's window allows viewing the whole diagnostic message, even when it is longer than the window's width.
=> Wrap text in telescope's previewer

lua/noice/view/scrollbar.lua
Due to the neovim upstream issue (https://github.com/neovim/neovim/issues/19464), creating a float window will always inherit the winbar from the parent window. As such, the window height need to be >=2 to prevent "E36: Not enough room" error.
=> fix: workaround E36: Not enough room errors

lua/noice/lsp/progress.lua
Some language servers are not in active list until initialization is done. 
For example clojure_lsp sends `$/progress` messages and activates itself (i.e. becomes available as active client) only when initialization is complete. In this case `get_active_clients` returns empty table. But `get_client_by_id` returns clojure client.
This PR replaces `vim.lsp.get_active_clients` with `vim.lsp.get_client_by_id` in progress handler.
=> fix: progress use vim.lsp.get_client_by_id

lua/noice/text/markdown.lua, tests/text/markdown_spec.lua
Hey folke, I recently made an upstream change for parsing the code fence language: https://github.com/neovim/neovim/pull/24364
This is the same fix for noice 🙂.
=> fix(lsp): allow whitespace info string in markdown

lua/noice/health.lua
Since #17 has been closed, this warning appears to be unnecessary
=> fix: remove old neovide compatibility warning

lua/noice/text/treesitter.lua
Fixes #570 
btw, https://github.com/neovim/neovim/commit/2ca076e45fb3f1c08f6a1a374834df0701b8d778 was what caused the regression.
=> fix(treesitter): parse injections

lua/noice/config/preset.lua
The following config fails:
```
require("noice").setup({
presets = {
foo = {}
}
})
```
with the error `"expected table, got nil"`
However, according to the doc (and the code) it should be acceptable to use a table in `presents`, the parameter `presets` is:
`@class NoicePresets: table<string, NoicePreset|boolean>`
This small PR fixes this issue.
=> fix: accept preset as a table

lua/noice/lsp/override.lua
https://github.com/folke/noice.nvim/blob/74c2902146b080035beb19944baf6f014a954720/lua/noice/lsp/override.lua#L20
`item.detail` sometimes is type of **table** and it will cause `ret:find` function throw a exception.
=> fix: check item.detail is type of table

lua/noice/lsp/progress.lua
With the new `LspProgress` notification, this `noice` implementation can be simplified a bit (and IMO it's safer to use the autocommand instead of overriding the handler).
Trying to make `noice` less hacky one PR at a time ;)
=> refactor(progress): use LspProgress notification

README.md, lua/noice/types/nui.lua, lua/noice/view/nui.lua
add an `hide_scrollbar` option for views like:
```lua
views = {
hover = {
hide_scrollbar = true,
}
},
```
that is good situation when i know there is something more or not, and save some columns of screen
=> feat: Support hide scrollbar for view

lua/noice/message/init.lua, lua/noice/text/block.lua, lua/noice/ui/cmdline.lua
I am not sure if the current approach is best, but i think other methods will result in duplicated code.
Fixes:
https://github.com/folke/noice.nvim/issues/650
https://github.com/folke/noice.nvim/issues/733
=> fix(input): don't filter ^M and <cr> for the command line

lua/noice/util/ffi.lua
Fixes #707
Ref https://github.com/luukvbaal/statuscol.nvim/issues/33#issuecomment-1481125976
=> fix(cmdpreview): read the variable `cmdpreview` in nvim-0.9+ on windows

lua/noice/lsp/progress.lua
On nvim 0.10-dev, there is a (breaking) change: the `data` table now
contains `params` instead of `result` for ProgressParams.
See neovim/neovim#28632
Ref #590
Fixes #793
=> fix(progress): Change LspProgress data field `result` to `params`

lua/noice/source/notify.lua
level argument defaults to `info` from `get_level` function, making `level` optional to avoid warning.
=> fix: level argument in notify is optional

lua/noice/text/format/init.lua
```lua
require("noice").setup {
format = { 
telescope = { '{date} ', '{event} ', '{title} ', '{message}' },
telescope_preview = {
' {date} ',
-- '{level} ',
'{event}',
{ '{kind}', before = { '.', hl_group = 'NoiceFormatKind' } },
' {title}',
'\n [{cmdline}]',
'\n {message}',
},
},
}
```
The config.format doesn't work.
=> fix: config.format doesn't work

lua/noice/lsp/format.lua
This is, for now, a quick fix for #819 - I would love to have a discussion of a better way to handle it. It works, but it's a dirty band-aid.
=> fix(markdown): ignore empty completion documentation tables

README.md
Option `smart_move` was deprecated since b6ae820190dd166d6ebae408d65f2551e37c7bf2
=> docs: remove deprecated option `smart_move`

lua/noice/types/nui.lua, lua/noice/ui/popupmenu/nui.lua
#603  Added the `scrollbar` option which was only available for certain views, and was not utilized within the popupmenu views. With this fix, popupmenu will honour the scrollbar option as well.
```
views = {
popupmenu = {
scrollbar = false,
}
},
```
=> feat(popupmenu): add option to hide scrollbar in popupmenu views.

lua/noice/message/init.lua, lua/noice/view/init.lua
Using `vim.b` variables seems slow for big tables. This PR improves performance of command output redirection (and possibly other places). From my tests this is an order of 20 sec -> 4 sec.
Also, it looks like the current code sometimes assumes that `vim.b[buf].messages` is a list of buffers, while it is a list of message ids. I also changed it from a list to a set, because it's mostly used for random access.
This helps in case described here: https://github.com/folke/noice.nvim/issues/332 (filetype is still applied many times, but from my recent benchmarks it seems that `vim.b.messages` had bigger impact).
=> perf(message): replace vim.b.messages with lua variable

lua/noice/message/router.lua
`NoiceRouteConfig.view` can be empty / `nil` as the check in `M.add()` sets it to nil if the view doesn't exist.
```lua
---@param route NoiceRouteConfig
---@param pos? number
function M.add(route, pos)
local ret = {
filter = route.filter,
opts = route.opts or {},
view = route.view and View.get_view(route.view, route.opts) or nil,
}
if ret.view == nil then
ret.opts.skip = true
end
```
=> fix(types): route.view can be empty / nil

lua/noice/lsp/init.lua
Fixes a warning notification for the first hover/signature help notification on nightly now that `offset_encoding` is required for `make_position_params`
=> fix(lsp): support mixed encoding for lsp clients

lua/noice/integrations/fzf.lua
`FzfWin:update_title` and `FzfWin:update_scrollbar` were changed to `FzfWin:update_preview_title` and `FzfWin:update_preview_scroolbar` since ibhagwan/fzf-lua@fc70792718d4a41101956c10ec04b6bf6a258777
It will make an error when opening message history with fzf-lua `:Noice fzf`
```
Error executing vim.schedule lua callback: ...hare/nvim/lazy/noice.nvim/lua/noice/integrations/fzf.lua:75: attempt to call method 'update__title' (a nil value)
stack traceback:
...hare/nvim/lazy/noice.nvim/lua/noice/integrations/fzf.lua:75: in function 'populate_preview_buf'
...hare/nvim/lazy/fzf-lua/lua/fzf-lua/previewer/builtin.lua:377: in function 'populate_preview_buf'
...hare/nvim/lazy/fzf-lua/lua/fzf-lua/previewer/builtin.lua:394: in function ''
vim/_editor.lua: in function ''
vim/_editor.lua: in function …
```
=> fix(fzf-lua): update `update_title` and `update_scrollbar` to `update_preview_title` and `update_preview_scrollbar`

lua/telescope/_extensions/noice.lua
Since commit [742610e](https://github.com/folke/noice.nvim/commit/742610e9958ad4f1146983db2e7356c8105a441c), extmark's hl_group can now be specified directly as an ID. This change ensures that if the hl_group is provided as a number (ID), it is resolved to its name using `synIDattr` for correct handling.
Fixes: #1024
=> fix(telescope): handle hl_group ID correctly in picker

lua/noice/integrations/fzf.lua
`<leader>snt` wasn't working properly
- the same fzf compatibility update as https://github.com/folke/noice.nvim/pull/1034
- the hl_group update from https://github.com/folke/noice.nvim/pull/1032 but for `fzf.lua`
Those PRs should probably merged instead of this, but the hl_group update one also needs to update `lua/noice/integrations/fzf.lua`
Figured I'd submit this to bump visibility of the issue.
https://github.com/folke/noice.nvim/issues/1029
https://github.com/folke/noice.nvim/issues/1024
=> feat(fzf): fix fzf integration
